spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/product
    username: soukaina
    password: soukaina
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8705